/**
 * Player engine voice.
 *
 * No usable engine loops exist on disk (the bank has two short ElevenLabs
 * one-shots, `engine_idle` / `engine_rev`, which are neither seamless nor
 * pitch-stable — looping them gives a repeating swell, which is worse than a
 * synth), so this is a physically-motivated synth rather than a sampler.
 *
 * What makes it read as an engine rather than a sawtooth on a frequency ramp:
 *
 * 1. It runs at the *firing* frequency (rpm/60 × cylinders/2), not at "RPM", and
 *    the harmonic stack is generated by fanning one ConstantSourceNode through
 *    fixed ratio gains into every oscillator's `frequency`. Previously each
 *    oscillator got its own `setTargetAtTime` with a *different* time constant,
 *    so during acceleration the "harmonics" were not actually harmonic — they
 *    slid apart and the stack detuned into a chord. One control signal makes the
 *    ratios exact by construction and costs one param write per frame instead
 *    of five.
 * 2. Fixed formant resonances the sweeping harmonics pass *through*. A filter
 *    that tracks pitch sounds synthetic; a pipe resonance that stays put while
 *    the engine climbs through it is what makes it sound like an object.
 * 3. Layer weights driven by RPM *and* load independently, so lifting at
 *    7000 rpm and idling at 900 do not produce the same timbre at different
 *    pitches.
 * 4. A real overrun state: harmonics collapse, induction noise takes over, and
 *    the exhaust crackles.
 */

import { noiseOffset, sharedNoise } from "./noise";

const IDLE_RPM = 850;
const MAX_RPM = 7400;
/** 4-stroke V8: two revolutions per cycle, eight fires → rpm/60 × 4. */
const FIRE_PER_RPM = 1 / 15;

export interface EngineInput {
  /** Engine is running and audible (racing / countdown / paused). */
  active: boolean;
  /** 0..1 road speed against the class maximum. */
  speed01: number;
  /** 0..1 raw throttle. */
  throttle: number;
  brake: boolean;
  boost: boolean;
  drifting: boolean;
  /** 1..5 discrete gear, from the driver. */
  gear: number;
  /** 0..1 fraction through the current gear, from the driver. */
  gearFrac: number;
  dt: number;
}

/**
 * Where the needle lands immediately after an upshift. Without this the engine
 * fell to idle at every shift point, because `gearFrac` restarts at zero — so a
 * car at 90% of top speed in fifth sounded exactly like one sitting on the grid,
 * and the overrun state could never engage at the top of a gear.
 */
const SHIFT_FLOOR = 0.36;
/** First gear starts at a real idle; nothing has been shifted out of yet. */
const IDLE_FLOOR = 0.015;
const REDLINE = 0.94;

export class EngineVoice {
  private ctx: BaseAudioContext;
  private rpmCs: ConstantSourceNode;
  private oscs: OscillatorNode[] = [];
  private gSub: GainNode;
  private gMain: GainNode;
  private gBeat: GainNode;
  private gH2: GainNode;
  private gH3: GainNode;
  private plate: BiquadFilterNode;
  private rasp: BiquadFilterNode;
  private oscTrim: GainNode;
  private gIntake: GainNode;
  private gOver: GainNode;
  private gTurbo: GainNode;
  private out: GainNode;

  private lastCrackle = 0;
  /** Smoothed in JS so the crackle rate and the mix agree on the same value. */
  private overrun = 0;
  private rpm01 = 0;

  constructor(ctx: BaseAudioContext, dests: AudioNode[]) {
    this.ctx = ctx;
    const noise = sharedNoise(ctx);

    this.out = ctx.createGain();
    this.out.gain.value = 0;
    for (const d of dests) this.out.connect(d);

    // --- control signal -----------------------------------------------------
    this.rpmCs = ctx.createConstantSource();
    this.rpmCs.offset.value = IDLE_RPM * FIRE_PER_RPM;
    const ratio = (k: number) => {
      const g = ctx.createGain();
      g.gain.value = k;
      this.rpmCs.connect(g);
      return g;
    };
    const rHalf = ratio(0.5);
    const rOne = ratio(1);
    const rTwo = ratio(2);
    const rThree = ratio(3);
    const rPlate = ratio(5.5);
    const rIntake = ratio(2.4);
    const rTurbo = ratio(13);

    // --- harmonic stack -----------------------------------------------------
    const osc = (type: OscillatorType, src: GainNode, detune = 0) => {
      const o = ctx.createOscillator();
      o.type = type;
      // Intrinsic value must be zero: the ratio gain is the only thing allowed
      // to set pitch, otherwise 440 Hz leaks in on top of every harmonic.
      o.frequency.value = 0;
      o.detune.value = detune;
      src.connect(o.frequency);
      this.oscs.push(o);
      return o;
    };
    const gain = (v: number) => {
      const g = ctx.createGain();
      g.gain.value = v;
      return g;
    };

    // Half-order sine is the V8 lope — the offbeat component that makes a big
    // engine sound uneven rather than like a buzzer.
    this.gSub = gain(0.3);
    this.gMain = gain(0.4);
    // Second unison voice, ~13 cents sharp. Cylinders never fire at identical
    // pressure, and that beating is most of the "many pistons" impression.
    this.gBeat = gain(0.16);
    this.gH2 = gain(0.06);
    this.gH3 = gain(0.01);

    osc("sine", rHalf).connect(this.gSub);
    osc("sawtooth", rOne).connect(this.gMain);
    osc("sawtooth", rOne, 13).connect(this.gBeat);
    osc("square", rTwo).connect(this.gH2);
    osc("sawtooth", rThree, -7).connect(this.gH3);

    const sum = gain(1);
    this.gSub.connect(sum);
    this.gMain.connect(sum);
    this.gBeat.connect(sum);
    this.gH2.connect(sum);
    this.gH3.connect(sum);

    // Throttle plate: cutoff rides both engine speed (via the control signal)
    // and load (set per frame). Closing it off-throttle is most of the overrun.
    this.plate = ctx.createBiquadFilter();
    this.plate.type = "lowpass";
    this.plate.frequency.value = 400;
    this.plate.Q.value = 0.7;
    rPlate.connect(this.plate.frequency);
    sum.connect(this.plate);

    // Fixed formants. These do not track pitch — that is the entire point.
    const formant = (f: number, q: number, g: number) => {
      const b = ctx.createBiquadFilter();
      b.type = "peaking";
      b.frequency.value = f;
      b.Q.value = q;
      b.gain.value = g;
      return b;
    };
    const pipe = formant(118, 3.4, 8); // exhaust pipe half-wave resonance
    const body = formant(470, 2.1, 5); // airbox / engine bay
    this.rasp = formant(1750, 1.5, 2); // hard edge, opens under load

    this.oscTrim = this.ctx.createGain();
    this.oscTrim.gain.value = 1;
    this.plate.connect(pipe);
    pipe.connect(body);
    body.connect(this.rasp);
    this.rasp.connect(this.oscTrim);
    this.oscTrim.connect(this.out);

    // --- noise layers -------------------------------------------------------
    const noiseSrc = ctx.createBufferSource();
    noiseSrc.buffer = noise;
    noiseSrc.loop = true;

    // Induction: band tracks engine speed, level tracks load. This is the layer
    // that makes full throttle sound like air being eaten.
    const intakeBp = ctx.createBiquadFilter();
    intakeBp.type = "bandpass";
    intakeBp.frequency.value = 220;
    intakeBp.Q.value = 0.8;
    rIntake.connect(intakeBp.frequency);
    this.gIntake = gain(0);
    noiseSrc.connect(intakeBp);
    intakeBp.connect(this.gIntake);
    this.gIntake.connect(this.out);

    // Overrun: fixed mid band, deliberately *not* pitch-tracked — engine braking
    // is mechanical and exhaust noise, not combustion.
    const overBp = ctx.createBiquadFilter();
    overBp.type = "bandpass";
    overBp.frequency.value = 820;
    overBp.Q.value = 0.9;
    this.gOver = gain(0);
    noiseSrc.connect(overBp);
    overBp.connect(this.gOver);
    this.gOver.connect(this.out);

    // Turbo: narrow whistle well above the harmonic stack.
    const turboBp = ctx.createBiquadFilter();
    turboBp.type = "bandpass";
    turboBp.frequency.value = 2400;
    turboBp.Q.value = 9;
    rTurbo.connect(turboBp.frequency);
    this.gTurbo = gain(0);
    noiseSrc.connect(turboBp);
    turboBp.connect(this.gTurbo);
    this.gTurbo.connect(this.out);

    this.rpmCs.start();
    noiseSrc.start();
    for (const o of this.oscs) o.start();
  }

  /** Normalised engine speed, for anything that wants to follow the revs. */
  getRpm01() {
    return this.rpm01;
  }

  update(t: number, s: EngineInput) {
    if (!s.active) {
      this.out.gain.setTargetAtTime(0, t, 0.09);
      this.gIntake.gain.setTargetAtTime(0, t, 0.09);
      this.gOver.gain.setTargetAtTime(0, t, 0.09);
      this.gTurbo.gain.setTargetAtTime(0, t, 0.09);
      this.overrun = 0;
      return;
    }

    // Standing revs: at rest the gear fraction is pinned at 0, so without this
    // the engine ignores the throttle entirely until the car is already moving.
    const stall = 1 - Math.min(1, s.speed01 * 11);
    const floor = s.gear <= 1 ? IDLE_FLOOR : SHIFT_FLOOR;
    const rpm01 = Math.max(
      0,
      Math.min(
        1,
        floor +
          s.gearFrac * (REDLINE - floor) +
          stall * s.throttle * 0.55 +
          s.throttle * 0.06 +
          (s.boost ? 0.1 : 0) +
          (s.drifting ? 0.1 : 0) -
          (s.brake ? 0.06 : 0),
      ),
    );
    this.rpm01 = rpm01;
    const rpm = IDLE_RPM + (MAX_RPM - IDLE_RPM) * rpm01;
    this.rpmCs.offset.setTargetAtTime(rpm * FIRE_PER_RPM, t, 0.055);

    const load = Math.max(
      s.throttle,
      s.boost ? 1 : 0,
      s.drifting ? 0.6 : 0,
    );
    // Overrun only exists with revs on the clock and a closed throttle. Slewed
    // in JS (not just on the param) because the crackle rate reads the same
    // value and a stepped target would make the crackle burst in clumps.
    const overTarget =
      (1 - s.throttle) * Math.max(0, Math.min(1, (rpm01 - 0.24) / 0.45));
    const k = Math.min(1, s.dt * 7);
    this.overrun += (overTarget - this.overrun) * k;
    const over = this.overrun;

    // Layer crossfade. Low weight is the idle lope, mid is the on-cam pull.
    const low = (1 - rpm01) * (1 - rpm01);
    const mid = rpm01 * (0.35 + 0.65 * load);

    this.gSub.gain.setTargetAtTime(0.16 + low * 0.42, t, 0.05);
    this.gMain.gain.setTargetAtTime(0.3 + load * 0.24, t, 0.045);
    this.gBeat.gain.setTargetAtTime(0.1 + mid * 0.26, t, 0.05);
    this.gH2.gain.setTargetAtTime(0.04 + mid * 0.4, t, 0.045);
    this.gH3.gain.setTargetAtTime(0.005 + mid * rpm01 * 0.34, t, 0.045);
    // Off-throttle the combustion harmonics fall away, they do not just get
    // quieter — the noise layers below take over the same energy.
    this.oscTrim.gain.setTargetAtTime(1 - over * 0.55, t, 0.06);

    this.plate.frequency.setTargetAtTime(
      260 + load * 1500 - over * 180,
      t,
      0.05,
    );
    this.rasp.gain.setTargetAtTime(1 + load * rpm01 * 9, t, 0.08);

    this.gIntake.gain.setTargetAtTime(
      (0.02 + load * 0.13) * (0.3 + s.speed01 * 0.9),
      t,
      0.05,
    );
    this.gOver.gain.setTargetAtTime(over * 0.075 * (0.4 + rpm01), t, 0.07);
    this.gTurbo.gain.setTargetAtTime(
      (s.boost ? 0.045 : 0.008) * load * rpm01,
      t,
      0.12,
    );

    const level =
      0.05 +
      s.speed01 * 0.13 +
      load * 0.13 +
      rpm01 * 0.05 +
      (s.boost ? 0.09 : 0);
    this.out.gain.setTargetAtTime(level, t, 0.04);

    // Exhaust crackle. Poisson-ish against dt so the rate is frame-rate
    // independent, plus a hard floor between bursts so a 240 Hz frame cannot
    // turn it into a buzz.
    if (over > 0.4 && rpm01 > 0.4 && t - this.lastCrackle > 0.055) {
      if (Math.random() < over * s.dt * 11) {
        this.lastCrackle = t;
        this.crackle(t, over);
      }
    }
  }

  /**
   * Three nodes per pop, released by `onended`. Bounded by the 55 ms floor
   * above, so worst case is ~18 short-lived nodes/second and only while the
   * player is off the throttle at speed.
   */
  private crackle(t: number, amount: number) {
    const ctx = this.ctx;
    const buf = sharedNoise(ctx);
    const dur = 0.02 + Math.random() * 0.03;
    const src = ctx.createBufferSource();
    src.buffer = buf;
    const bp = ctx.createBiquadFilter();
    bp.type = "bandpass";
    bp.frequency.value = 900 + Math.random() * 2200;
    bp.Q.value = 1.4;
    const g = ctx.createGain();
    const peak = 0.04 + amount * 0.09 * Math.random();
    g.gain.setValueAtTime(peak, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    src.connect(bp);
    bp.connect(g);
    g.connect(this.out);
    src.onended = () => {
      try {
        g.disconnect();
      } catch {
        /* already torn down */
      }
    };
    src.start(t, noiseOffset(buf, dur));
    src.stop(t + dur + 0.01);
  }
}
